import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/molecules/Navbar/Navbar";
import Footer from "@/components/molecules/Footer/Footer";
import TopBanner from "@/components/molecules/TopBanner/TopBanner"
import AdBanner from "@/components/molecules/AdBanner/AdBanner"
import styles from "@/styles/Layout.module.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "OTCB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className={styles.container}>
          <div className={styles.content}>
            <TopBanner/>
            <Navbar />
            <div className={styles.childrenWrapper}>
              {children}
            </div>
            <div className={styles.adBannerWrapper}>
            <AdBanner />
          </div>
            <div className={styles.footerWrapper}>
                <Footer />
              </div>          
              </div>
        </div>
      </body>
    </html>
  );
}
